Update scratterwalk_map(), scatterwalk_unmap() usage
CC      arch/x86/crypto/aesni-intel_glue.o
arch/x86/crypto/aesni-intel_glue.c: In function ‘ccm_calculate_auth_mac’:
arch/x86/crypto/aesni-intel_glue.c:396:21: error: void value not ignored as it ought to be
396 |                 src = scatterwalk_map(&walk);
    |                     ^
arch/x86/crypto/aesni-intel_glue.c:401:35: error: passing argument 1 of ‘scatterwalk_unmap’ from incompatible pointer type [-Wincompatible-pointer-types]
401 |                 scatterwalk_unmap(src);
    |                                   ^~~
    |                                   |
    |                                   u8 * {aka unsigned char *}
In file included from arch/x86/crypto/aesni-intel_glue.c:31:
./include/crypto/scatterwalk.h:150:59: note: expected ‘struct scatter_walk *’ but argument is of type ‘u8 *’ {aka ‘unsigned char *’}
150 | static inline void scatterwalk_unmap(struct scatter_walk *walk)
    |                                      ~~~~~~~~~~~~~~~~~~~~~^~~~
arch/x86/crypto/aesni-intel_glue.c:403:17: error: implicit declaration of function ‘scatterwalk_done’; did you mean ‘scatterwalk_ffwd’? [-Wimplicit-function-declaration]
403 |                 scatterwalk_done(&walk, 0, len);
    |                 ^~~~~~~~~~~~~~~~

The calling convention was changed in
commit 7450ebd29cd9 ("crypto: scatterwalk - simplify map and unmap calling convention")